# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'appAme' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for appAme
  pod 'CLTypingLabel', '~> 0.4.0'

  target 'appAmeTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'appAmeUITests' do
    # Pods for testing
  end

end
